repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.2
    hooks:
      - id: ruff-check
        args: [--fix]
        files: ^infrared_protocols/
      - id: ruff-format
        files: ^infrared_protocols/

  - repo: https://github.com/DetachHead/basedpyright-prek-mirror
    rev: 1.38.1
    hooks:
      - id: basedpyright
        files: ^infrared_protocols/
