name: CI

on: [push, pull_request]

jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Run prek
        uses: j178/prek-action@cbc2f23eb5539cf20d82d1aabd0d0ecbcc56f4e3 # v2.0.2
        env:
          RUFF_OUTPUT_FORMAT: github

  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13", "3.14"]
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e "."
          pip install -e ".[dev]"
      - name: Test with pytest
        run: |
          pytest --log-cli-level=debug

  release:
    runs-on: ubuntu-latest
    concurrency: release
    environment: python-semantic-release
    if: github.ref == 'refs/heads/main'
    needs: [prek, pytest]
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Generate Token
        id: app-token
        uses: actions/create-github-app-token@v2.2.1
        with:
          app-id: ${{ secrets.PSR_APP_ID }}
          private-key: ${{ secrets.PSR_PRIVATE_KEY }}
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Python Semantic Release
        id: release
        uses: python-semantic-release/python-semantic-release@v10.5.3
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          changelog: false
      - name: Publish package PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: steps.release.outputs.released == 'true'
